# Generated by Django 4.2.3 on 2023-07-15 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inskrywing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inskrywing',
            name='inhoud',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inskrywing',
            name='skeppings_tyd',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 22, 0, 47, 306096)),
        ),
    ]
