# Generated by Django 4.2.3 on 2024-01-02 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
