# Generated by Django 4.2.3 on 2024-01-03 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_alter_entry_entry_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
    ]
