# Generated by Django 4.2.3 on 2024-01-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_remove_entry_category_remove_entry_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='language',
            new_name='tags',
        ),
    ]
