# Generated by Django 4.2.3 on 2024-02-25 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0012_rename_user_entry_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='update_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
