# Generated by Django 4.2.3 on 2024-01-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_entry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('news', 'News'), ('events', 'Events'), ('family', 'Family'), ('travel', 'Travel'), ('work', 'Work')], max_length=50, null=True),
        ),
    ]
