# Generated by Django 4.2.3 on 2024-01-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_entry_title_alter_entry_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
