# Generated by Django 4.2.3 on 2024-03-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='surname',
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_use_timezone',
            field=models.BooleanField(default=True),
        ),
    ]
